### ISSUE TITLE
Why should we rep you

### ISSUE THREAD

**Issue by ZentifyZ** [Rogue619Z/Rust-internal-base#1]
Why should we rep you when this is a stolen project, none of this code is urs. and why even release this piece of garbage lol, mr yacrum. go on ur main github account, no need to make alts.

**Comment by Rogue619Z** [comment]
i dont understand who you are

you should rep me because i uploaded it?

**Comment by YamieYT** [comment]
Yacrum posted the source on his discord lmao idk wtf this little kid is goin on with yacrum he jus a hater

**Comment by Rogue619Z** [comment]
> Yacrum posted the source on his discord lmao idk wtf this little kid is goin on with yacrum he jus a hater
🤝
